// runs.go: the only store functions this iteration needs - create a scrape_runs
// row at the start of a run and finish it at the end.
//
// design: Observability / scrape_runs fields.
package store

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// ScrapeRun mirrors a row of the scrape_runs table (001_init.sql). Nullable
// columns are pointers so a caller can distinguish NULL from a zero value.
type ScrapeRun struct {
	ID            int64
	PlatformID    int64
	StartedAt     time.Time
	FinishedAt    *time.Time
	Status        string
	ItemsFound    int64
	ItemsInserted int64
	ItemsUpdated  int64
	ErrorText     *string
}

// StartRun inserts the scrape_runs row that marks a run as in flight and
// returns its id. started_at is generated by SQLite (not by Go) so it uses the
// same clock and format as every other timestamp in the schema, and the value
// returned here is the authoritative run timestamp - it is also what the raw
// payload filename is derived from.
//
// design-gap: the build spec said started_at would come from a column default,
// but scrape_runs.started_at is declared "TEXT NOT NULL" with no DEFAULT in
// 001_init.sql (unlike companies.created_at and friends). The timestamp is
// therefore produced by strftime(...) inside this INSERT, which keeps the value
// database-generated without altering the schema.
//
// design: Run lifecycle step 3 - this row is committed before the network is
// touched, so a crash is visible as a stuck 'running' row rather than a gap.
func StartRun(ctx context.Context, db *sql.DB, platformID int64) (int64, time.Time, error) {
	const q = `
INSERT INTO scrape_runs (platform_id, started_at, status)
VALUES (?, strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'running')
RETURNING id, started_at`

	var (
		id        int64
		startedAt string
	)
	if err := db.QueryRowContext(ctx, q, platformID).Scan(&id, &startedAt); err != nil {
		return 0, time.Time{}, fmt.Errorf("insert scrape_runs: %w", err)
	}

	// The default is strftime('%Y-%m-%dT%H:%M:%fZ','now'), i.e. RFC3339 UTC with
	// millisecond precision.
	ts, err := time.Parse(time.RFC3339, startedAt)
	if err != nil {
		return 0, time.Time{}, fmt.Errorf("parse started_at %q returned by the database: %w", startedAt, err)
	}
	return id, ts, nil
}

// StartCompanyRun inserts the scrape_runs row that marks a per-company listings scrape as in flight,
// recording which company the run is for. It is StartRun plus the company_id link added by migration
// 016; a batch sweep needs that link to decide, per company, whether a previous run already finished
// ok or already left a browser-use trace, so it can skip companies that already worked.
func StartCompanyRun(ctx context.Context, db *sql.DB, platformID, companyID int64) (int64, time.Time, error) {
	const q = `
INSERT INTO scrape_runs (platform_id, started_at, status, company_id)
VALUES (?, strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'running', ?)
RETURNING id, started_at`

	var (
		id        int64
		startedAt string
	)
	if err := db.QueryRowContext(ctx, q, platformID, companyID).Scan(&id, &startedAt); err != nil {
		return 0, time.Time{}, fmt.Errorf("insert company scrape_runs: %w", err)
	}
	ts, err := time.Parse(time.RFC3339, startedAt)
	if err != nil {
		return 0, time.Time{}, fmt.Errorf("parse started_at %q returned by the database: %w", startedAt, err)
	}
	return id, ts, nil
}

// FinishRun writes the terminal state of a run: finished_at, status, the three
// counters, and the error text. status is constrained by the schema's CHECK
// (status IN ('running','ok','error')); it is deliberately not re-validated here.
//
// design-gap: the build spec's signature for this function omitted errText, but
// the design doc requires the failure path to record a single-line condition +
// error message in scrape_runs.error_text. The parameter is therefore included;
// passing nil records NULL (the success case).
func FinishRun(ctx context.Context, db *sql.DB, runID int64, status string, itemsFound, itemsInserted, itemsUpdated int64, errText *string) error {
	const q = `
UPDATE scrape_runs
   SET finished_at    = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
       status         = ?,
       items_found    = ?,
       items_inserted = ?,
       items_updated  = ?,
       error_text     = ?
 WHERE id = ?`

	// design: Failure policy ("DB is locked") - one retry of the single failing
	// statement after 1s before giving up.
	err := RunWithOneRetry(ctx, func() error {
		_, execErr := db.ExecContext(ctx, q, status, itemsFound, itemsInserted, itemsUpdated, errText, runID)
		return execErr
	})
	if err != nil {
		return fmt.Errorf("update scrape_runs id=%d: %w", runID, err)
	}
	return nil
}

// FinishValidationRun writes the terminal state of a browser-use validation run.
//
// It is a separate function from FinishRun rather than a wider FinishRun because the counters mean
// different things. A resolution run's items_inserted/items_updated count URL writes; a validation
// run writes no URL at all, and its outcome is a three-way split - confirmed, wrong, unverifiable -
// that the older two counters cannot express. Widening FinishRun would have forced every existing
// caller to pass zeros for columns it has no opinion about.
func FinishValidationRun(ctx context.Context, db *sql.DB, runID int64, status string,
	found, confirmed, wrong, unverifiable int64, errText *string) error {
	const q = `
UPDATE scrape_runs
   SET finished_at        = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
       status             = ?,
       items_found        = ?,
       items_inserted     = ?,
       items_updated      = 0,
       items_wrong        = ?,
       items_unverifiable = ?,
       error_text         = ?
 WHERE id = ?`

	err := RunWithOneRetry(ctx, func() error {
		_, execErr := db.ExecContext(ctx, q, status, found, confirmed, wrong, unverifiable, errText, runID)
		return execErr
	})
	if err != nil {
		return fmt.Errorf("update validation scrape_runs id=%d: %w", runID, err)
	}
	return nil
}

// StartDryRun inserts a run row marked dry_run = 1.
//
// A dry run records its attempts like any other run - that is the point of a pre-flight pass, since
// counters without the rows behind them cannot be inspected - and the flag is how those rows stay
// out of production reporting. It shares StartRun's ordering guarantee: the row is committed before
// anything is fetched.
func StartDryRun(ctx context.Context, db *sql.DB, platformID int64) (int64, time.Time, error) {
	const q = `
INSERT INTO scrape_runs (platform_id, started_at, status, dry_run)
VALUES (?, strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'running', 1)
RETURNING id, started_at`

	var (
		id        int64
		startedAt string
	)
	if err := db.QueryRowContext(ctx, q, platformID).Scan(&id, &startedAt); err != nil {
		return 0, time.Time{}, fmt.Errorf("insert dry scrape_runs: %w", err)
	}
	ts, err := time.Parse(time.RFC3339, startedAt)
	if err != nil {
		return 0, time.Time{}, fmt.Errorf("parse started_at %q returned by the database: %w", startedAt, err)
	}
	return id, ts, nil
}

// IsDryRun reports whether a run is a dry run. Reporting queries use it to exclude dry-run attempts
// from production figures.
func IsDryRun(ctx context.Context, db *sql.DB, runID int64) (bool, error) {
	var dry int
	if err := db.QueryRowContext(ctx,
		`SELECT dry_run FROM scrape_runs WHERE id = ?`, runID).Scan(&dry); err != nil {
		return false, fmt.Errorf("read dry_run for run %d: %w", runID, err)
	}
	return dry == 1, nil
}

// CancelRun marks a running run as error with a "cancelled by user" note, and reports whether it
// changed anything. The `WHERE status = 'running'` guard makes it a no-op on a run that already
// finished, so a stop that races the job's own FinishRun cannot resurrect or corrupt a terminal row.
func CancelRun(ctx context.Context, db *sql.DB, runID int64) (bool, error) {
	const q = `
UPDATE scrape_runs
   SET finished_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
       status      = 'error',
       error_text  = 'cancelled by user'
 WHERE id = ? AND status = 'running'`

	res, err := db.ExecContext(ctx, q, runID)
	if err != nil {
		return false, fmt.Errorf("cancel run %d: %w", runID, err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return false, fmt.Errorf("cancel run %d: rows affected: %w", runID, err)
	}
	return n > 0, nil
}

// ReconcileStaleRuns closes out every run still marked 'running' and reports how many it touched.
//
// Called once at startup: a fresh server process means any previously-running job was killed with
// it (the server reaps a job's run in a goroutine, and a killed process never runs that goroutine),
// so those rows would otherwise stay stuck in 'running' forever. Marking them as error with a note
// is the recovery path - the operator can then re-run, and the job skips work it already completed.
func ReconcileStaleRuns(ctx context.Context, db *sql.DB) (int64, error) {
	const q = `
UPDATE scrape_runs
   SET finished_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
       status      = 'error',
       error_text  = 'interrupted by restart'
 WHERE status = 'running'`

	res, err := db.ExecContext(ctx, q)
	if err != nil {
		return 0, fmt.Errorf("reconcile stale runs: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("reconcile stale runs: rows affected: %w", err)
	}
	return n, nil
}
