// runs.go: the only store functions this iteration needs - create a scrape_runs
// row at the start of a run and finish it at the end.
//
// design: Observability / scrape_runs fields.
package store

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// ScrapeRun mirrors a row of the scrape_runs table (001_init.sql). Nullable
// columns are pointers so a caller can distinguish NULL from a zero value.
type ScrapeRun struct {
	ID            int64
	PlatformID    int64
	StartedAt     time.Time
	FinishedAt    *time.Time
	Status        string
	ItemsFound    int64
	ItemsInserted int64
	ItemsUpdated  int64
	ErrorText     *string
}

// StartRun inserts the scrape_runs row that marks a run as in flight and
// returns its id. started_at is generated by SQLite (not by Go) so it uses the
// same clock and format as every other timestamp in the schema, and the value
// returned here is the authoritative run timestamp - it is also what the raw
// payload filename is derived from.
//
// design-gap: the build spec said started_at would come from a column default,
// but scrape_runs.started_at is declared "TEXT NOT NULL" with no DEFAULT in
// 001_init.sql (unlike companies.created_at and friends). The timestamp is
// therefore produced by strftime(...) inside this INSERT, which keeps the value
// database-generated without altering the schema.
//
// design: Run lifecycle step 3 - this row is committed before the network is
// touched, so a crash is visible as a stuck 'running' row rather than a gap.
func StartRun(ctx context.Context, db *sql.DB, platformID int64) (int64, time.Time, error) {
	const q = `
INSERT INTO scrape_runs (platform_id, started_at, status)
VALUES (?, strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'running')
RETURNING id, started_at`

	var (
		id        int64
		startedAt string
	)
	if err := db.QueryRowContext(ctx, q, platformID).Scan(&id, &startedAt); err != nil {
		return 0, time.Time{}, fmt.Errorf("insert scrape_runs: %w", err)
	}

	// The default is strftime('%Y-%m-%dT%H:%M:%fZ','now'), i.e. RFC3339 UTC with
	// millisecond precision.
	ts, err := time.Parse(time.RFC3339, startedAt)
	if err != nil {
		return 0, time.Time{}, fmt.Errorf("parse started_at %q returned by the database: %w", startedAt, err)
	}
	return id, ts, nil
}

// FinishRun writes the terminal state of a run: finished_at, status, the three
// counters, and the error text. status is constrained by the schema's CHECK
// (status IN ('running','ok','error')); it is deliberately not re-validated here.
//
// design-gap: the build spec's signature for this function omitted errText, but
// the design doc requires the failure path to record a single-line condition +
// error message in scrape_runs.error_text. The parameter is therefore included;
// passing nil records NULL (the success case).
func FinishRun(ctx context.Context, db *sql.DB, runID int64, status string, itemsFound, itemsInserted, itemsUpdated int64, errText *string) error {
	const q = `
UPDATE scrape_runs
   SET finished_at    = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
       status         = ?,
       items_found    = ?,
       items_inserted = ?,
       items_updated  = ?,
       error_text     = ?
 WHERE id = ?`

	// design: Failure policy ("DB is locked") - one retry of the single failing
	// statement after 1s before giving up.
	err := RunWithOneRetry(ctx, func() error {
		_, execErr := db.ExecContext(ctx, q, status, itemsFound, itemsInserted, itemsUpdated, errText, runID)
		return execErr
	})
	if err != nil {
		return fmt.Errorf("update scrape_runs id=%d: %w", runID, err)
	}
	return nil
}
